project: 
  title: &project_title alphasocket/dockerized-redis-alpine
  codename: &project_codename redis-alpine
  description: Redis service with pass configurable in ENV
  
#
# Init builder
#
general:
  envvars:
    docker:
      user: &general_docker_user 03192859189254 
    keys:
      True: "True"
      false: "False"
      dev: "dev"
      prd: "prd"
    
#
# Build process
# Creates dockerfile and file used in it
#
build:
  envvars:
    name: *project_codename
    branch:
      valueFromCommand: 'git rev-parse --abbrev-ref HEAD'
    commit:
      valueFromCommand: 'git rev-parse --short HEAD'
    version:
      valueFromCommand: 'echo $BUILD_BRANCH | cut -d \- -f 1'
    env:
      valueFromCommand: 'env=$(echo $BUILD_BRANCH | cut -d \- -f 2); [ "$env" = "$BUILD_VERSION" ] && echo $GENERAL_KEYS_PRD || echo $env'
    paths:
      config:
        redis: /etc/redis/
    # Redis
    redis:        
      port: 6379
    # Docker
    dockerfile:
      image: redis:alpine
      ports:
        main: $BUILD_REDIS_PORT
      cmd: 'docker-entrypoint.sh $CONFIG_PATHS_CONFIG_REDIS --requirepass \"$CONFIG_REDIS_PASS\"'
  imports:
    - "imports/templates:/usr/local/templates"

#
# Setup process injected in dockerfile
#
setup:
  # Setup env 
  envvars:
    dependencies:
      setup: ""
      config: gettext
    paths:
      config:
        redis: /etc/redis/
  # Setup Processes
  processes:
    - title: "Install dependencies"
      commands: 
        - "apk add --no-cache $SETUP_DEPENDENCIES_CONFIG $SETUP_DEPENDENCIES_SETUP"

#
# Config process run just before the entrypoint
#
config:
  # Config env 
  envvars:
    paths:
      templates:
        redis: /usr/local/templates/redis.conf
      config:
        redis: $SETUP_PATHS_CONFIG_REDIS/redis.conf
    redis:
      persistence: 'yes'
      pass: redis-default-pass
  
  processes:
    - title: "Create server conf"
      commands:
       - envsubst < $CONFIG_PATHS_TEMPLATES_REDIS > $CONFIG_PATHS_CONFIG_REDIS

test:
  envvars:
    name: $BUILD_NAME
    port: 30080
    dockerfile:
      tag: 
        user: *general_docker_user
        name: $BUILD_NAME
        version: $BUILD_BRANCH

  processes:
    #
    # Starting
    #
    - title: "Starting container" 
      commands:
        - TEST_CONTAINER_REDIS_ID=$(
            docker run 
              -d --name=$TEST_NAME
              -p 127.0.0.1:${TEST_PORT}:${BUILD_DOCKERFILE_PORTS_MAIN}
              -e CONFIG_REDIS_PASS=${TEST_PASS}
              ${TEST_DOCKERFILE_TAG_USER}/${TEST_DOCKERFILE_TAG_NAME}:${TEST_DOCKERFILE_TAG_VERSION}
          )
        - TEST_CONTAINER_REDIS_STATUS=$(sleep 1 && docker inspect -f '{{.State.Running}}' $TEST_CONTAINER_REDIS_ID)

    - title: "Testing container"
      shell_condition: '! "$TEST_CONTAINER_REDIS_STATUS" = "true"'
      commands:
        - echo "Container failed, print logs and exiting\n"
        - docker logs $TEST_CONTAINER_REDIS_ID
        - exit 1

    #
    # TESTING
    #
    - title: "Testing service"
      commands:
        - sudo apt install redis-cli -y
        - PING_RESULT=$( redis-cli ping -p ${TEST_PORT} -a ${TEST_PASS} )

    - title: "Checking"
      shell_condition: '! "$PING_RESULT" = "pong"'
      commands:
        - echo "### Test failed, received ${PING_RESULT} printing log\n" 
        - docker logs $TEST_CONTAINER_REDIS_ID
        - exit 1

    - title: "Success"
      shell_condition: '"$PING_RESULT" = "pong"'
      commands:
        - echo "### Test Succeeded, received ${PING_RESULT}\n" 
